### ISSUE TITLE
[Bug/Crash]: Integrated Tunnels Crashing due to what seems to be Null PartState references.

### ISSUE THREAD

**Issue by Lanse505** [CyclopsMC/IntegratedTunnels#165]
#### Issue type:

- :bug: Bug

____

#### Short description:
Pretext: We are using Sponge and are actively working on debugging any sponge related issues ahead of time and providing information on how to fix sponge related issues to server networks who are going to be using this pack.

Tagging @gabizou in-case he has anything to interject with in regards to this issue.
Or if any questions regarding sponge were to surface.

This issue however we've found has no code interaction between IT/ID and Sponge.
Meaning this is with most certainly not a sponge-specific issue, but it might be "extrapolated" by Sponge.

We're running into weird NPE crashes related to Integrated Tunnels.
More Precisely it's related to both IEnergyTarget and IFluidTarget:
[Energy](http://paste.ubuntu.com/p/2PqgMk55Rz/)
[Fluids](http://paste.ubuntu.com/p/VQGpywZWv2/)

For some reason, it's returning null to the part?
[Energy](https://github.com/CyclopsMC/IntegratedTunnels/blob/master-1.12/src/main/java/org/cyclops/integratedtunnels/part/aspect/IEnergyTarget.java#L34)
[Fluid](https://github.com/CyclopsMC/IntegratedTunnels/blob/master-1.12/src/main/java/org/cyclops/integratedtunnels/part/aspect/IFluidTarget.java#L41)

#### Steps to reproduce the problem:

The steps to produce is kind of weird.
Currently, it seems to be done using an Astral Sorcery set-up for growing gems and using the Integrated Tunnels to move items and fluids in and out of the world.

We haven't had time to do a dedicated system to test it.

The thing is, it seems to get more crashy and more prone to unstable-ness the more crashes happen. And we're currently at the state where it crashes whenever **anyone** logs on to the server and loads a build using Integrated Tunnels.

#### Expected behaviour:
No Crash, and things working as intended.

____

#### Versions:
- Integrated Dynamics: 1.12.2-1.0.11
- This mod: 1.12.2-1.6.8
- Minecraft: 1.12.2
- Forge: 14.23.5.2810
- Sponge: 1.12.2-2825-7.1.6-RC3716

#### Log file:

[Energy Log](http://paste.ubuntu.com/p/2PqgMk55Rz/)
[Energy Line](https://github.com/CyclopsMC/IntegratedTunnels/blob/master-1.12/src/main/java/org/cyclops/integratedtunnels/part/aspect/IEnergyTarget.java#L34)

[Fluid Log](http://paste.ubuntu.com/p/VQGpywZWv2/)
[Fluid Line](https://github.com/CyclopsMC/IntegratedTunnels/blob/master-1.12/src/main/java/org/cyclops/integratedtunnels/part/aspect/IFluidTarget.java#L41)

**Comment by rubensworks** [comment]
That's odd. The only explanation I have is that there's some kind of chunkloading issue when spongeforge is used. I'll have a look at it soon.

**Comment by rubensworks** [comment]
@Lanse505 I may have a fix for this problem, could you try out IT build 329 to see if this fixes your problem? (see readme for link to dev builds)

**Comment by Lanse505** [comment]
Ill have our server owner throw it on the dev server. Ill get back to you once I have an answer to if its fixed

**Comment by gabizou** [comment]
Ah hi, yes, I've got an explanation for why a chunk seemingly is having an issue, it may be that when there's a request for a chunk load during [specific states of the game, Sponge goes to deny those requests with an empty chunk](https://github.com/SpongePowered/SpongeCommon/commit/9aebb5b80d1760ec5715cd6f99fe3e301685ec5f). The reasoning behind this is that performance of Chunk GC'ing (unloading) over a single tick ends up getting spammed when there's excessive requests for one off instances that don't intend to keep those chunks loaded. It's possible that by getting an empty chunk, the "part" is null and causing an NPE in your code.

If I can find out, what/when does your code specifically check for part states to where we might be able to return loadable chunks instead of empty chunks? Of course, the alternative is your workaround fix where a null check will perform the same resolution.

**Comment by rubensworks** [comment]
Thanks for the information @gabizou! If @Lanse505 still has problems with the latest IT dev build, I'll give you some more information regarding part state checking.
