### ISSUE TITLE
Item dupe bug

### ISSUE THREAD

**Issue by Naosyth** [CyclopsMC/IntegratedTunnels#169]
#### Issue type:

- :bug: Bug

____

#### Short description:

Item interfaces attached to blocks that are able to automatically pull from adjacent blocks can dupe items.

#### Steps to reproduce the problem:

1. Place a block down that can pull from adjacent inventories. A Thermal Expansion Item Allocator works well for this.
2. Set one side of the allocator to push an pull
3. Enable auto input and output (not necessary to set both, you get slightly different dupe behavior depending on how it's set)
4. Set the allocator's input limit higher than its output limit
5. Place an integrated tunnels item interface on the side you configured (all you need is an interface, not even a cable)
6. Place a single stackable item in the allocator
7. Profit

GIF of the process:
![dupe-bug-simplified](https://user-images.githubusercontent.com/1323992/59545192-003f4900-8ed0-11e9-8082-abff6c016cc6.gif)

I don't have any other mods that provide auto input/output in this pack, so I can't test against another mod to verify 100% that this is Integrated Dynamic's fault, but I was not able to get the item allocator to duplicate its content by auto pulling or pushing to anything other than an item interface.

#### Expected behaviour:

Items should not be duplicated when pushing/pulling via an item interface

____

#### Versions:

- Integrated Dynamics: 1.12.2-1.0.14
- Integrated Crafting: 1.12.2-1.0.7
- Integrated Terminals: 1.12.2-1.0.8
- Integrated Tunnels: 1.12.2-1.6.9
- Thermal Expansion: 5.5.3.41
- Minecraft: 1.12.2
- Forge: 14.23.5.2837

**Comment by rubensworks** [comment]
That's very bad.

It's possible though that my recent change in Common Capabilities may have fixed this problem. Could you try the latest dev build (see readme) to see if this fixes the problem for you? https://github.com/CyclopsMC/CommonCapabilities

<blockquote><img src="https://avatars2.githubusercontent.com/u/11808375?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/CommonCapabilities">CyclopsMC/CommonCapabilities</a></strong></div><div>Forge Capabilities that can be shared by multiple mods. - CyclopsMC/CommonCapabilities</div></blockquote>

**Comment by Naosyth** [comment]
The dev build fixed that particular dupe, but I found a slight variation on it that still worked: https://streamable.com/2nhn3

By attaching a player simulator, I was able to dupe or delete items depending on if the side facing the interface was set as an input or an output

<blockquote><img src="https://cdn-b-east.streamable.com/image/2nhn3.jpg?token=GSmekDKY6NryN2fqDrNo8w&expires=1560624360" width="48" align="right"><div>Streamable</div><div><strong><a href="https://streamable.com/2nhn3">dupe - Streamable</a></strong></div><div>Check out this video on Streamable using your phone, tablet or desktop.</div></blockquote>

**Comment by rubensworks** [comment]
Thanks for checking, let's leave this issue open then.

**Comment by Naosyth** [comment]
It appears the dupe still exists, albeit in a slightly different form:
![dupe-bug](https://user-images.githubusercontent.com/1323992/60392380-4abaeb00-9ab6-11e9-88a3-e405dffff406.gif)

With a single interface, it didn't dupe anything, but once I put multiple interfaces on the same item allocator, it started duping items again.

**Comment by rubensworks** [comment]
Hmm, thanks for letting me know again.

**Comment by rubensworks** [comment]
Ok, so I've been digging around a bit, and it looks like this is an issue with Thermal Expansion.

Since their issue tracker seems to be closed, let me ping @KingLemming here directly to see if this indeed correct.

So what I think is going wrong here is this:

1. The item allocator calls `extractItem` on each side: https://github.com/CoFH/ThermalExpansion/blob/1.12/src/main/java/cofh/thermalexpansion/block/device/TileItemBuffer.java#L128
2. Before any extraction is being done, the stack inside the current allocator slot is being stored (and copied): https://github.com/CoFH/CoFHCore/blob/1.12/src/main/java/cofh/core/block/TileInventory.java#L32
3. Internally, this allocator will call `extractItem` on IT's item interface: https://github.com/CoFH/CoFHCore/blob/1.12/src/main/java/cofh/core/block/TileInventory.java#L59
4. After this extraction is being done, the previously stored stack is being incremented with the extracted item: https://github.com/CoFH/CoFHCore/blob/1.12/src/main/java/cofh/core/block/TileInventory.java#L61
5. Finally, the stored stack is placed again inside the inventory.

However, step 4 is the place where things are going wrong. Since step 3 extracts from the IT interface, IT will recursively extract again from the first slot inside the item allocator, which will _modify_ the item in the first slot. However, since step 2 caches this item beforehand, and step 4 only modifies this cached item, any external changes (by IT) to this item are being ignored.

A simple solution would be to just call `insertItem` in step 4 instead of modifying the cached item.

<blockquote><img src="https://avatars0.githubusercontent.com/u/7482560?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/CoFH/ThermalExpansion">CoFH/ThermalExpansion</a></strong></div><div>Contribute to CoFH/ThermalExpansion development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars0.githubusercontent.com/u/7482560?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/CoFH/CoFHCore">CoFH/CoFHCore</a></strong></div><div>Contribute to CoFH/CoFHCore development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars0.githubusercontent.com/u/7482560?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/CoFH/CoFHCore">CoFH/CoFHCore</a></strong></div><div>Contribute to CoFH/CoFHCore development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars0.githubusercontent.com/u/7482560?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/CoFH/CoFHCore">CoFH/CoFHCore</a></strong></div><div>Contribute to CoFH/CoFHCore development by creating an account on GitHub.</div></blockquote>

**Comment by rubensworks** [comment]
Looks like this won't be fixed in CoFH 1.12 anymore. Fingers crossed for 1.15.
