### ISSUE TITLE
Some slots 'hog' item transfer when exporting item by item type with slot specified

### ISSUE THREAD

**Issue by met4000** [CyclopsMC/IntegratedTunnels#203]
#### Issue type:

- :bug: Bug

____

#### Short description:

When using subnetworks to export multiple specific items into specific slots of a dispenser, slots `2`, `5`, and `8` (the 'right-hand side slots') seem to 'hog' or 'jam' item transfer.

#### Steps to reproduce the problem:

1. Place output container (tested with droppers and dispensors, similar behaviour may exist with chests, etc.) and item source container
2. Construct array of item exporters pointing into item interfaces
3. Connect the interface subnetwork to the output container with an item interface, and the exporter subnetwork to the item source container with an item interface
4. Using the `Export Item` aspect, provide unique target slots for each exporter, and use a variable card to set each exporter to a specific item type (tested using various wool colourings)

See below image for example setup (the one used to test this);
![image](https://user-images.githubusercontent.com/15624876/95698225-dc327a00-0c73-11eb-9a04-3a130ebe2e44.png)
(in the image, each block in the 3x3 grid (as observed from the side with the dispenser) represent that slot in the dispenser; i.e. currently the interfaces for slots `2`, `5`, and `8` are disconnected from the interface subnetwork)

#### Observed Behaviour:
Item transfer will only 'properly' occur when the exporter(s) or interface(s) for slots `2`, `5`, and `8` are disconnected from the rest of their subnetwork. If any 1 of those slots is connected, then item transfer to all other slots ceases, but occurs for that slot. If 2 or more of those slots are connected, no item transfer occurs.

#### Expected behaviour:
All item[ type]s transferred to set slot(s).
____

#### Versions:

- Minecraft: 1.12.2
- Forge: 14.23.5.2852
- Cyclops Core: 1.12.2-1.6.2
- ID: 1.12.2-1.1.4
- ID-Compat: 1.0.0
- Tunnels: 1.12.2-1.6.11
- Tunnels-Compat: 1.0.0

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by met4000** [comment]
Some additional testing using importers yielded similar results, but with slot `7` additionally 'hogging'/'jamming' item transfer.

![image](https://user-images.githubusercontent.com/15624876/95928329-aae0b800-0df3-11eb-98df-d96e5217a023.png)

**Comment by rubensworks** [comment]
So this is actually due to intentional behaviour.
When using item interfaces to re-expose an inventory, the slots that the network exposes do not necessarily correspond to the inventory's slots.
Since several other item interfaces are in use in your case, also these will cause slots to be exposed to the network.
You can confirm this by reading the item interface with an inventory reader, and there will be more than 9 slots.

I would suggest to use something like a Capability Proxy to expose an inventory via multiple sides so that you can achieve fine-grained slot insertion for all slots.

If I (or someone else) ever get to #69, this will behave as you would expect.
