### ISSUE TITLE
World Item Importer crashing with boolean

### ISSUE THREAD

**Issue by Kyiki-Nasoka** [CyclopsMC/IntegratedTunnels#231]
#### Issue type:

- :bug: Bug 

____

#### Short description:
World Item importer causes server crash when a blank card (boolean true) is placed in aspect "Import all items from Entity"

#### Steps to reproduce the problem:

1. see above

#### Expected behaviour:
Items to be imported from inventory / equipped slots

____

#### Versions:

- This mod: Integrated Tunnel 1.16.5-1.8.2, Integrated Dynamics 1.16.5.1.8.4
- Minecraft: 1.16.5
- Forge: 36.1.25

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Do you have a crashlog?

**Comment by GzusO** [comment]
Here is a crash log of it. 
https://pastebin.com/pHAQLUpa

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/pHAQLUpa">ID - World Item Import Crash on Import All Items from Entities - Pastebin.com</a></strong></div><div>Pastebin.com is the number one paste tool since 2002. Pastebin is a website where you can store text online for a set period of time.</div></blockquote>

**Comment by rubensworks** [comment]
Thanks!
