### ISSUE TITLE
Fluid transfer from a RealFilingCabinet can cause crashes

### ISSUE THREAD

**Issue by tommyTT** [CyclopsMC/IntegratedTunnels#24]
I have already posted an issue here bafomdad/realfilingcabinet#16 but also wanted to make you aware of this. The problem is that the code in [TunnelFluidHelpers](https://github.com/CyclopsMC/IntegratedTunnels/blob/master-1.11/src/main/java/org/cyclops/integratedtunnels/core/TunnelFluidHelpers.java#L48) doesn't expect the returned IFluidTankProperties to be null and causes a crash if they are. I don't know the Forge rules for fluid stack handling, but since there is no FluidStack.EMPTY (yet) that I could find, I suspect that it would be safer to guard against these situations in IT too.

**Comment by rubensworks** [comment]
AFAIK a `IFluidTankProperties` is not allowed to be null, but the RFC mod author seems to have fixed it already in the next version, so that's good :-)

I won't add a safeguard, since otherwise IT just wouldn't be able to interact with the tank, while it should, and clearly is being caused by a bug in the target tank.
