### ISSUE TITLE
Inconsistent crash

### ISSUE THREAD

**Issue by bangplaysgames** [CyclopsMC/IntegratedTunnels#253]
#### Issue type:

- :bug: Bug 

____

#### Short description:

It's very inconsistent, but there is a crash that keeps happening on my server caused by Integrated Tunnels.  It's possible that this is also related to Ender Rift, as that is the storage device that my item interface is attached to, and its behavior is pretty drastically different from other storage devices.

#### Steps to reproduce the problem:

1. Attach Item Interface to Ender Rift
2. Insert and extract items via Storage Terminal
3. It's random, it seems, when the issue shows itself.
4. Sometimes it simply stops receiving any items and shows "####/0" as the number of items in the terminal and the maximum."  Sometimes it hard crashes the server.

#### Expected behaviour:

Not have this crash.

____

#### Versions:

- This mod: 1.16.5-1.8.9
- Minecraft: 1.16.5
- Forge: 36.2.31

#### Log file:

https://pastebin.com/gSx2p6Dw

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This _may_ be a bug in Ender Rift.
IT throws this error if item extraction during simulation and actual execution is different (because IT depends on this in it's item routing logic)
https://github.com/CyclopsMC/CommonCapabilities/blob/48eb24b736a3da2a068bc6272edf91db5898adee/src/main/java/org/cyclops/commoncapabilities/ingredient/storage/IngredientComponentStorageWrapperHandlerItemStack.java#L205-L208

Could you open an issue on their tracker to see where the problem may lie?

<blockquote><img src="https://opengraph.githubassets.com/3d23eb396a3375803f68bf0cfff7d186f575fa69fb60852d1ccaeb5ea5fd1303/CyclopsMC/CommonCapabilities" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/CommonCapabilities">CommonCapabilities/IngredientComponentStorageWrapperHandlerItemStack.java at 48eb24b736a3da2a068bc6272edf91db5898adee · CyclopsMC/CommonCapabilities</a></strong></div><div>Forge Capabilities that can be shared by multiple mods. - CommonCapabilities/IngredientComponentStorageWrapperHandlerItemStack.java at 48eb24b736a3da2a068bc6272edf91db5898adee · CyclopsMC/CommonCap...</div></blockquote>
