### ISSUE TITLE
Suggestion: some kind of regulator that reads all slots in an inventory

### ISSUE THREAD

**Issue by satsujinke** [CyclopsMC/IntegratedTunnels#26]
I'd really like a way to import/export all items but have it check if it already has a full stack in the target inventory and if it does then the system ignores that item. Currently I can have a reader check a single slot and make a boolean based on that but I want something that will allow me to import/export all items but only maintain one stack of each in the target inventory. Basically what I want is something like Steve's Factory Manager, Translocators and the old Rationing Pipe from Extra Utilities.

**Comment by rubensworks** [comment]
The goal of this mod is to make the player figure out interesting logic processes, instead of having a single plug-and-play system.
And since your goal is a bit too specific, so I won't add an aspect for this, because this would otherwise clutter the aspect list.
You can actually already do that by reading the list of items, filtering out the items that have a full stack present, and importing/exporting for that list.
