### ISSUE TITLE
Clicking on storage terminal causes server to crash

### ISSUE THREAD

**Issue by AntonLM** [CyclopsMC/IntegratedTunnels#260]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I have 9 netherite chests attached to the Tunnels storage network (since before the update). I had emptied the contents of another netherite chest (full from clearing a dungeon) into available space in the 9 chests - directly, not via the terminal, as it was quicker. When I had finished that, I clicked to open the terminal, and the server crashed immediately. Admin rebooted, and I tried again, same effect. Admin suggested it might be something newly added to the network, so after reboot I removed all the interfaces from the chests and, for good measure, all the logic cables, leaving the terminal unattached, and chests also unattached. Clicked again to open the terminal, and the server crashed immediately again. 

#### Steps to reproduce the problem:

1. R-click on terminal - server crashes immediately.

#### Expected behaviour:

R-click on terminal should open the storage network, as it did before.
____

#### Versions:

- This mod: IntegratedTunnels-1.19.2-1.8.16.jar Sep 17, 2022
- Minecraft: 1.19
- Forge: 43.1.38

 I have reported it on the ATM Discord. Had no response.
 I cannot modify the pack - it's on a multiplayer server.
 as above

#### Log file:
I don't have access to that. If it's needed, I can ask our admin to provide it?

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> I don't have access to that. If it's needed, I can ask our admin to provide it?

Yep, that would be great, otherwise there's nothing I can do.

**Comment by jstansel** [comment]
This may be the same issue as ATM-8 # 112 https://github.com/AllTheMods/ATM-8/issues/112

**Comment by mindlessjohnny** [comment]
> > I don't have access to that. If it's needed, I can ask our admin to provide it?
> 
> Yep, that would be great, otherwise there's nothing I can do.

[crash-2022-10-15_11.16.04-server.txt](https://github.com/CyclopsMC/IntegratedTunnels/files/9792587/crash-2022-10-15_11.16.04-server.txt)
[2022-10-15-1.log](https://github.com/CyclopsMC/IntegratedTunnels/files/9792588/2022-10-15-1.log)

I just tried to update my server to the latest and experienced the same crash when trying to access my Storage Terminal. I've attached the main server log and the crash report.

**Comment by Jophire** [comment]
Just for completeness. It also occurs when using the portable terminal.
[Server Log](https://paste.shockbyte.com/ijemetizuhuruququsay)
[Crash Report](https://github.com/CyclopsMC/IntegratedTunnels/files/9795545/crash-2022-10-16_19.53.03-server.txt)

^
Should be basically identical to above. Also running ATM8 version 0.1.3 and the issue only started occurring after upgrading from 0.0.16 to 0.1.1.

**Comment by Kefisu** [comment]
Can confirm I am experiencing this issue too.

To give you some more logs:
Server log: https://pastebin.com/dK0LV8Yf 
Crash log: https://pastebin.com/F2AWQCBd

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/dK0LV8Yf">Server log - Pastebin.com</a></strong></div><div>Pastebin.com is the number one paste tool since 2002. Pastebin is a website where you can store text online for a set period of time.</div></blockquote>
<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/F2AWQCBd">Crash log - Pastebin.com</a></strong></div><div>Pastebin.com is the number one paste tool since 2002. Pastebin is a website where you can store text online for a set period of time.</div></blockquote>

**Comment by rubensworks** [comment]
Should be fixed in https://github.com/CyclopsMC/IntegratedTerminals/commit/f9812f0a196e03b9682589c22e6c418341ab9d3a
