### ISSUE TITLE
Crash when dispensing Botania's Wand of the Forest using a World Item Exporter

### ISSUE THREAD

**Issue by MaienM** [CyclopsMC/IntegratedTunnels#261]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Crash when using a Wand of the Forest from Botania in the Place Item Entity action of the World Item Exporter with the Dispense option enabled.

This occurs because the wand implements `OptionalDispenseItemBehavior`, and inside this behaviour it attempts to get the facing of the dispenser (`world.getBlockState(source.getPos()).getValue(DispenserBlock.FACING);`).

#### Steps to reproduce the problem:

1. Create a basic network with an Item Interface connected to a chest, and a World Item Exporter.
1. Create a variable card holding the Wand of the Forest Item from Botania.
1. Store the Wand of the Forest in the chest.
1. Put the variable card into the Place Item Entity action of the World Item Exporter.
1. Enable the Dispense option of this action.

#### Expected behaviour:

I expected the World Item Exporter to use the wand the same way a regular dispenser would, which is to activate a block (a Runic Altar in this case) as if the user had right-clicked it with the wand.

____

#### Versions:

- This mod: 1.8.15
- Minecraft: 1.18.2
- Forge: 40.1.84

#### Log file:

https://dpaste.com/72GXV24D2

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Could you report this to Botania's issue tracker, and link back to here?

They seem to be retrieving the blockstate from the world (via `world.getBlockState(source.getPos())`) instead of retrieving it from the `BlockSource` via `getBlockState()`.
This is needed because ID simulates the dispenser block, without being an actual dispenser block itself (this approach is compatible with the vanilla dispenser behaviors).

**Comment by TheRealWormbo** [comment]
This should finally get fixed with the next release for 1.20.1, now that someone reported it to Botania, as previously suggested.
