### ISSUE TITLE
World Item Importer doesn't import from player

### ISSUE THREAD

**Issue by LindaJuffermans** [CyclopsMC/IntegratedTunnels#317]
#### Issue type:

- :bug: Bug 

____

#### Short description:

A World Item Importer set to Import All Items From Entities, will not extract the items from a player's inventory if the player is standing on front of the importer.

#### Steps to reproduce the problem:

1. Create a simple network with a Chest, Item Interface and World Item Importer
2. Insert a blank Variable Card in the slot for Import All Items From Entities
3. Drop a filled shulker in front of the World Item Importer; observe it's being emptied into your chest
4. Stand in front of the World Item Importer; observe it is not taking anything from your inventory

![image](https://github.com/user-attachments/assets/66d24ac2-008a-4f67-aa08-a9397b91044e)
![image](https://github.com/user-attachments/assets/850194bf-6b1a-4b4a-b2a5-c33d9bc3d1e9)

Note: I tried both surival and creative; I also tried standing a block lower.

#### Expected behaviour:

I would expect my inventory to be emptied into the chest.
____

#### Versions:

- This mod: 1.8.32
- Integrated Dynamics: 1.24.2
- Minecraft: 1.20.1
- Mod loader version: Forge 47.3.0

#### Log file:

[debug.log](https://github.com/user-attachments/files/18266182/debug.log)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I just had a look at this, and it seems I forgot how this worked.
But due to how (Neo)Forge handles player item capabilities, the direction your importer/exporter is pointing towards matters.
If you want to access the main player inventory, you need to target the part to the top (or bottom?) side. (which you can also modify in the part settings)
North/east/south/west only target the armor inventory if I remember correctly.

**Comment by LindaJuffermans** [comment]
👍 Up/Down works for my inventory and all sides for the armour slots. Thanks.
