### ISSUE TITLE
Target multiple parts to one side

### ISSUE THREAD

**Issue by Nanabell** [CyclopsMC/IntegratedTunnels#44]
At the moment you can use ID with IT easily to connect to to the Improved Blast Furnace but since the furnace has specific in/outputs you can only connect to those so if you want to fully automate it you need to have IT Interfaces etc. on everyone  
Top => iron, coal coke in  
Front => steel out  
Back => slag out  
That works wonderful but that leaves no room to connect for example an inventory reader to only insert as much iron as you have coal coke in the furnace.  
I don't know if there is any possibility that an inventory reader can read those inventories while not directly connected to it or if IE is preventing that, just thought i give it as an idea since the normal blast furnace and coke oven have no problem with the extra reader as its not side dependent.
![2017-07-28_16 29 32](https://user-images.githubusercontent.com/13600006/28721951-3ec4f8e0-73b2-11e7-9348-58fccb13bba5.png)
![2017-07-28_16 29 43](https://user-images.githubusercontent.com/13600006/28721956-43fe1a8a-73b2-11e7-9428-8f8e440297c6.png)

**Comment by Nanabell** [comment]
🤔 i should have probably opened that on Integrated Dynamics not Tunnels. my bad.. i'd move it if you want

**Comment by rubensworks** [comment]
No, it's fine, you can leave the issue here :-)

So in general, you want to attach _multiple_ parts to the same side?
Something like that is not possible at the moment, but I guess I should foresee something that can handle cases like these.
I'll think about it.

In the meantime you could use a [Capability Proxy](https://minecraft.curseforge.com/projects/capabilityproxy) that will expose one side of a target to five more sides.

**Comment by Nanabell** [comment]
dude.. :thonk: do you have a mod for everything ? tyvm

**Comment by rubensworks** [comment]
Note to self: adding an option to change the facing side via the gui might also be a good solution.

**Comment by rubensworks** [comment]
Same issue exists at CyclopsMC/IntegratedDynamics#278, closing this in favor of that one.
