### ISSUE TITLE
Game crash using Integrated dynamaics/tunnels

### ISSUE THREAD

**Issue by nicolas-evra** [CyclopsMC/IntegratedTunnels#84]
#### Issue type:

- :bug: Bug

____
#### Short description:
I'd like to create a automatic canola energy system using Integrated Dynamics and Tunnels.
I'm setting up the system using a world fluid importer and exporter, a block reader and an entity exporter.
I'm creating a variable with the block reader et a constant with air with the materialiser.
After that using the programming tool, If the block in front of the black reader == "air" then send Refined canola Oil. (this gives me a boolean variable.
But when I'm placing this boolean in the world liquid exporter, the game crashes.

#### Expected behaviour:
If I'm correct, it should of put Refined Oil into the hole every time there is air (nothing)

#### Actual behaviour:
The Game crashes

#### Steps to reproduce the problem:

1. setting up the system using a world fluid importer and exporter, a block reader and an entity exporter.
2. Create a variable with the block reader and a constant with air with the materialiser.
3. Use the programming tool, 
If the block in front of the black reader == "air" then send Refined canola Oil. (this gives me a boolean variable.
4. Place the boolean into the luquid world exporter
____
#### Versions: 

_Exact versions of the following mods, not just *latest*._

- This mod: IntegratedDynamics-1.12.2-0.9.6 & IntegratedTunnels-1.12.2-1.3.5
- CyclopsCore: CyclopsCore-1.12.2-0.10.23
- Minecraft: 1.12.2
- Forge: (Don't know where to find the forge version, I'm using the modpack FTB Direwolf20 1.1.0 and tried with 1.2.0 crashes aswell)

#### Log file:

https://pastebin.com/B2q40BXx

**Comment by josephcsible** [comment]
What is an "entity exporter"? Neither Integrated Dynamics nor Integrated Tunnels adds an item by that name.

**Comment by josephcsible** [comment]
I did manage to reproduce this without that, though, so bug confirmed. Here's what I did exactly:
1. Created a network with a block reader, a variable store, a materializer, and a world fluid exporter
2. Materialized "air" from the block reader
3. Used == in the logic programmer on the block reader output and air
4. Put the block variable cards in the variable store
5. Placed the resulting card into the "Place All Fluids" slot in the world fluid exporter

Also, a much simpler way to cause it:
1. Place a cable
2. Attach a world fluid writer
3. Place a blank variable card in the "Place All Fluids" slot

Flagging as "major" because once you do this, attempting to reload the world will just result in it immediately crashing again.

I'm guessing this is related to 3efe9f6.

**Comment by nicolas-evra** [comment]
Hi.
Yes sorry I couldn't remember the exact name for the "entity exporter" I was reffering to the "World Item Exporter".

I'm glad that you have been able to reproduce the bug and I hope you will find a way to correct it because your mod is really cool and usefull.

Cheers
