### ISSUE TITLE
IInventory and ISidedInventory support

### ISSUE THREAD

**Issue by CplPibald** [CyclopsMC/IntegratedTunnels#88]
#### Issue type:
- :heavy_plus_sign: Feature request

There are still a number of mods out there that don't support the ItemHandler capability, and Integrated Tunnels can't integrate with [those mods](https://github.com/gkbm2013/tinker-IO/issues/60).  In an ideal world, all Forge mods should be updated to support Forge capabilities, but that isn't always practical.  Most other item transport mods that use IItemHandler also have a fallback to using the legacy inventory interfaces. 

This is a feature request to investigate adding legacy IInventory / ISidedInventory support to Integrated Tunnels.

**Comment by rubensworks** [comment]
Sorry, but I won't do that, as those interfaces are deprecated. It would require too much work to work on supporting something that has been deprecated for a long time already.

In order to handle those outdated mods, one could dynamically inject item handler capabilities for mods that do not support them. (Just like [Energy Synergy](https://minecraft.curseforge.com/projects/energysynergy) does for FE)

**Comment by josephcsible** [comment]
> (Just like Capability Proxy does for FE)

Huh? Where does it do that?

**Comment by rubensworks** [comment]
@josephcsible My bad, I meant Energy Synergy.
